# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       server.js
       package.json
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       dist/english-learning/browser/*
    targetFolder: '$(Build.ArtifactStagingDirectory)/app'
    flattenFolders: true
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: english-learning
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(731f386c-c9ca-4ecb-9288-a352e1a206c8)'
    appType: 'webAppLinux'
    WebAppName: 'english-test'
    packageForLinux: '$(System.DefaultWorkingDirectory)'
    RuntimeStack: 'NODE|18-lts'
    StartupCommand: 'yarn start'
    ScriptType: 'Inline Script'
    InlineScript: 'yarn install'
